# Generated by Django 3.2.13 on 2022-04-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='max_zoom',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='map',
            name='min_zoom',
            field=models.IntegerField(default=1),
        ),
    ]
