# Generated by Django 3.2.12 on 2022-04-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndmap', '0002_layer_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('darkred', 'Darkred'), ('orange', 'Orange'), ('green', 'Green'), ('darkgreen', 'Darkgreen'), ('blue', 'Blue'), ('purple', 'Purple'), ('darkpurple', 'Darkpurple'), ('cadetblue', 'Cadetblue')], default='blue', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='icon',
            field=models.CharField(default='circle', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='icon_color',
            field=models.CharField(default='#FFFFFF', max_length=64),
            preserve_default=False,
        ),
    ]
