# Generated by Django 3.2.13 on 2022-04-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dndmap', '0003_party_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='link_to_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndmap.map'),
        ),
    ]
