# Generated by Django 3.2.12 on 2022-04-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndmap', '0003_auto_20220411_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='show_at_zoom_level',
            field=models.IntegerField(default=0),
        ),
    ]
