# Generated by Django 3.2.12 on 2022-08-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndmap', '0004_marker_link_to_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
    ]
