# Generated by Django 3.2.12 on 2022-04-12 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dndmap', '0004_layer_show_at_zoom_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='map',
            name='collaborators',
            field=models.ManyToManyField(related_name='map_collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
